#!/usr/bin/env python3
"""
sync_prompts.py — Extract all prompts from Meta-Lingo's MCP server and agent service,
then write them into PROMPTS.md in this directory.

Run from anywhere:
    python /Volumes/TL-TANIUM/Meta-Lingo-Electron/mcp-extension/sync_prompts.py

Or from the mcp-extension directory:
    python sync_prompts.py
"""
import ast
import inspect
import os
import re
import sys
import textwrap
from datetime import datetime
from pathlib import Path

# ── paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
BACKEND = PROJECT_ROOT / "backend"
TOOLS_DIR = BACKEND / "mcp_server" / "tools"
AGENT_SERVICE = BACKEND / "services" / "agent_service.py"
SERVER_PY = BACKEND / "mcp_server" / "server.py"
OUT_FILE = SCRIPT_DIR / "PROMPTS.md"

sys.path.insert(0, str(BACKEND))

# ── helpers ────────────────────────────────────────────────────────────────────

def _extract_string_constant(source: str, varname: str) -> str:
    """Extract the value of a module-level string constant by name."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return f"(parse error for {varname})"
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == varname:
                    if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                        return node.value.value
                    # Handle joined strings (implicit concatenation)
                    try:
                        return ast.literal_eval(node.value)
                    except Exception:
                        pass
    return f"(could not extract {varname})"


def _extract_tool_docstrings(tool_path: Path) -> list[tuple[str, str]]:
    """Return [(tool_name, docstring), ...] from a tool module file."""
    source = tool_path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []

    results = []
    # Tools are defined as async def inside a register(mcp, client) function
    for node in ast.walk(tree):
        if isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            # Skip 'register' wrapper and private helpers
            if node.name.startswith("_") or node.name == "register":
                continue
            docstring = ast.get_docstring(node) or ""
            if docstring:
                results.append((node.name, docstring))
    return results


def _section(title: str, level: int = 2) -> str:
    return f"\n{'#' * level} {title}\n"


def _prose_block(content: str) -> str:
    """Output prompt content as readable plain text, indented with > blockquote."""
    lines = content.strip().splitlines()
    # Blockquote keeps content visually distinct without hiding it in a code fence
    quoted = "\n".join(f"> {line}" if line.strip() else ">" for line in lines)
    return f"\n{quoted}\n"


def _tool_separator() -> str:
    return "\n" + "-" * 80 + "\n"


def _divider() -> str:
    return "\n---\n"


# ── main extraction ────────────────────────────────────────────────────────────

def build_prompts_md() -> str:
    lines: list[str] = []

    # Header
    lines.append("# Meta-Lingo Prompt Reference")
    lines.append(f"\n> Auto-generated by `sync_prompts.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}.  ")
    lines.append("> Edit the source files (agent_service.py, server.py, tools/*.py) — not this file.\n")
    lines.append(_divider())

    # ── 1. Agent System Prompt ──────────────────────────────────────────────────
    lines.append(_section("1. Agent System Prompt (`agent_service.py`)"))
    lines.append(
        "The system prompt injected at the start of every Agent Chat conversation.\n"
        "Defines Lemy's personality, tool usage rules, analysis logic, and output format standards.\n"
    )

    agent_src = AGENT_SERVICE.read_text(encoding="utf-8")
    sys_prompt = _extract_string_constant(agent_src, "SYSTEM_PROMPT")
    lines.append(_prose_block(sys_prompt))

    # zh hint (inside _build_system_prompt)
    zh_match = re.search(
        r'lang_hint\s*=\s*\(\s*((?:"[^"]*"\s*\n?\s*)+)\)',
        agent_src, re.DOTALL
    )
    if zh_match:
        raw = zh_match.group(1)
        try:
            zh_hint = ast.literal_eval("(" + raw + ")")
        except Exception:
            zh_hint = raw
        lines.append(_section("1.1 Chinese Mode Addendum (`_build_system_prompt`, zh branch)", level=3))
        lines.append(_prose_block(zh_hint if isinstance(zh_hint, str) else raw))

    lines.append(_divider())

    # ── 2. MCP Server Instructions ─────────────────────────────────────────────
    lines.append(_section("2. MCP Server Instructions (`server.py`)"))
    lines.append(
        "Injected as the MCP server `instructions` field — visible to Claude Desktop and\n"
        "other MCP clients when they connect. Provides tool usage strategy and workflow guidance.\n"
    )
    server_src = SERVER_PY.read_text(encoding="utf-8")

    instr_match = re.search(
        r'instructions\s*=\s*\(\s*((?:"[^"]*"(?:\s*\n\s*)?)+)',
        server_src, re.DOTALL
    )
    if instr_match:
        raw = instr_match.group(1).strip()
        try:
            instructions = ast.literal_eval("(" + raw + ")")
        except Exception:
            instructions = raw
        lines.append(_prose_block(instructions if isinstance(instructions, str) else raw))
    else:
        lines.append("*(Could not extract — check server.py)*\n")

    lines.append(_divider())

    # ── 3. Tool Docstrings ─────────────────────────────────────────────────────
    lines.append(_section("3. Tool Docstrings (per tool module)"))
    lines.append(
        "Each tool's docstring is its prompt — it tells the LLM when and how to use the tool,\n"
        "what parameters to pass, and what to expect in return.\n"
    )

    tool_files = sorted(TOOLS_DIR.glob("*.py"))
    tool_files = [f for f in tool_files if not f.name.startswith("_") and not f.name.startswith(".")]

    for tool_file in tool_files:
        module_name = tool_file.stem
        tools = _extract_tool_docstrings(tool_file)
        if not tools:
            continue

        lines.append(_section(f"3.{tool_files.index(tool_file) + 1} `{module_name}.py`", level=3))
        for tool_name, docstring in tools:
            lines.append(_section(f"`{tool_name}`", level=4))
            lines.append(_prose_block(textwrap.dedent(docstring)))
            lines.append(_tool_separator())

    lines.append(_divider())

    # ── 4. DMIP Embedded Procedure ─────────────────────────────────────────────
    lines.append(_section("4. DMIP Embedded Procedure (`tools/dmip.py`)"))
    lines.append(
        "The `_DMIP_PROCEDURE` constant is appended to every `dmip_analysis` tool output.\n"
        "It embeds the full DMIP four-dimension analysis framework directly into the model context.\n"
    )
    dmip_src = (TOOLS_DIR / "dmip.py").read_text(encoding="utf-8")
    dmip_proc = _extract_string_constant(dmip_src, "_DMIP_PROCEDURE")
    lines.append(_prose_block(dmip_proc))

    lines.append(_divider())

    # ── 5. Output Format Templates ─────────────────────────────────────────────
    lines.append(_section("5. Output Format Templates"))
    lines.append(
        "These templates are embedded in the SYSTEM_PROMPT (section 1) and enforce\n"
        "consistent output structure across all analysis types.\n"
    )
    lines.append("| Template | When to use |\n|----------|-------------|\n"
                 "| Single-text / corpus | Any corpus-level analysis tool result |\n"
                 "| Multi-text iteration | User requests 逐篇/every text/per-text loop |\n"
                 "| DMIP per-text | After each `dmip_analysis` call |\n")

    lines.append(_divider())
    lines.append(f"\n*Generated: {datetime.now().isoformat(timespec='seconds')}*\n")

    return "\n".join(lines)


# ── entry point ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"Extracting prompts from {BACKEND} ...")
    content = build_prompts_md()
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"✓ Written {len(content):,} chars → {OUT_FILE}")

    # Quick summary
    tool_count = sum(
        len(_extract_tool_docstrings(f))
        for f in sorted(TOOLS_DIR.glob("*.py"))
        if not f.name.startswith("_") and not f.name.startswith(".")
    )
    print(f"  • System prompt: {len(_extract_string_constant(AGENT_SERVICE.read_text(), 'SYSTEM_PROMPT')):,} chars")
    print(f"  • Tool docstrings: {tool_count} tools across {len(list(TOOLS_DIR.glob('[!_]*.py')))} modules")
